# Generated by Django 5.0.7 on 2024-07-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(verbose_name=255)),
                ('zipcode', models.BigIntegerField(verbose_name=6)),
                ('state', models.CharField(verbose_name=2)),
                ('appt_num', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(verbose_name=255)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(verbose_name=255)),
                ('last_name', models.CharField(verbose_name=255)),
                ('middle_init', models.CharField(verbose_name=2)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('number_of_employees', models.IntegerField()),
                ('rating', models.FloatField()),
                ('owner', models.CharField(verbose_name=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name=255)),
                ('in_stock', models.BigIntegerField()),
                ('rating', models.CharField()),
            ],
        ),
    ]
